config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #default route that the application takes and alias of home for the path
  root 'editor#index', as: 'home'

  #this needs to be above resources to be called correctly.
  get "editor/info", as: 'info'
  get "editor/:id/download", to: "editor#download", as: 'download'
  #creates most of the paths for the editor class
  resources :editor
  #the one that it didn't make but I needed
  post "editor/new"    => "editor#create"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/editor_controller.rb
class EditorController < ApplicationController
  def index
    @documents = Document.all
  end

  def new
    @document = Document.new
  end

  def show
    @document = Document.find(params[:id])
  end

  def create
    #this just outputs the properties of the object passed by the view as text.
    #render plain: params[:document].inspect
    @document = Document.new(document_params)

    #save the object
    if(@document.save)
      #redirect to that page
      redirect_to action: "show", id: @document.id
    else
      render 'new'
    end
  end

  def edit
    @document = Document.find(params[:id])
  end

  def update
    @document = Document.find(params[:id])

    if(@document.update(document_params))

      redirect_to action: "show", id: @document.id
    else
      render 'edit'
    end
  end

  def destroy
    @document = Document.find(params[:id])

    @document.destroy

    redirect_to home_path
  end

  def download
    @document = Document.find(params[:id])
    send_data @document.body,
              filename: "#{@document.title}.html",
              type: "text/html"
  end

  #method to say what paramaters are needed to create the object
  private def document_params
    params.require(:document).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  #a helper method to dynamically add the active class
  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end

end

app/helpers/editor_helper.rb
module EditorHelper
end

app/views/editor/edit.html.erb
<div class="header" align="center">
  <h2 class="bg-danger pt-2 pb-2">Edit File
</div>
<div class="container">
  <%= form_for :document,  :url => { :action => "update" }, :html => { :method => :patch} do |f| %>
    <% if @document.errors.any? %>
      <% @document.errors.full_messages.each do |m| %>
        <div class="alert alert-danger">
          <%= m %>
        </div>
      <% end %>
    <% end %>
    <h3>
      <%= f.label :title %><br />
    </h3>
    <h4>
      <%= f.text_field :title, class: "form-control" %>
    </h4>
    <h4>
      <%= f.label :body %><br />
      <select class="form-control" onchange="ChangeHighlighting()" id="highlight">
        <option value="htmlmixed">Select Language...</option>
        <option value="htmlmixed">
          html
        </option>
        <option value="text/javascript">
          javascript
        </option>
        <option value="text/x-haml">
          haml
        </option>
        <option value="text/x-ruby">
          Ruby
        </option>
        <option value="text/xml">
          xml
        </option>
      </select>
    </h4>
    <p>
      <%= f.text_area :body, class: 'form-control', rows: '10' %>
    </p>
    <p>
      <%= f.submit class: 'btn btn-success' %>
    </p>

  <% end %>
</div>

app/views/editor/index.html.erb
<div class="header" align="center">
	<h2 class="bg-danger pt-2 pb-2">Your Documents</h2>
</div>
<div class="container">
	<% @documents.each do |d| %>
		<div class="card bg-dark text-white">
			<div class="card-body">
				<h4>
					<%= d.title %>
				</h4>
				<%=raw d.body %>
				<br><br>
				<%= link_to "View", editor_path(d.id), :class => 'btn btn-info' %>
			</div>
		</div>
		<br>
	<% end %>
</div>

app/views/editor/info.html.erb
<div class="header" align="center">
  <h2 class="bg-danger pt-2 pb-2">Information</h2>
</div>
<div class="container">
  <div class="card bg-dark text-white">
      <div class="card-body">
        <h5>About Corundum</h5>
        Corundum is a Ruby/Rails based text editor that allows you to work on documents in a variety of languages (HTML, JavaScript, Haml, Ruby, XML) and save them with markdown automatically applied.<br>
        This editor also allows you to upload and edit text files, all saved to your computer on its own local server.<br>
        We use <a href=https://codemirror.net/>CodeMirror</a> as an inspiration for our editor.
        <h5>Shortcuts</h5>
        <a href=https://defkey.com/codemirror-shortcuts>Defkey.com List of Shortcuts</a>
      </div>
  </div>
</div>

app/views/editor/new.html.erb
<div class="header" align="center">
  <h2 class="bg-danger pt-2 pb-2">Add File</h2>
</div>
<div class="container">
  <%= form_for :document, path: "editor" do |f| %>
    <% if @document.errors.any? %>
      <% @document.errors.full_messages.each do |m| %>
        <div class="alert alert-danger">
          <%= m %>
        </div>
      <% end %>
    <% end %>
    <h3 class="text-muted">
      <%= f.label :title %><br />
    </h3>
    <h4>
      <%= f.text_field :title, class: "form-control" %>
    </h4>
    <h4 class="text-muted">
      <%= f.label :body %><br />
      <select class="form-control" onchange="ChangeHighlighting()" id="highlight">
        <option value="htmlmixed">Select Language...</option>
        <option value="htmlmixed">
          html
        </option>
        <option value="text/javascript">
          javascript
        </option>
        <option value="text/x-haml">
          haml
        </option>
        <option value="text/x-ruby">
          Ruby
        </option>
        <option value="text/xml">
          xml
        </option>
      </select>
    </h4>
    <p>
      <%= f.text_area :body, class: 'form-control', rows: '10' %>
    </p>
    <p>
      <input type="file" name="file" id="file" onchange="openFile(event)" class="btn btn-secondary">
      <br /><br>
      <%= f.submit class: 'btn btn-success' %>
    </p>
    <% end %>
</div>

app/views/editor/show.html.erb
<div class="header" align="center">
  <h2 class="bg-danger pt-2 pb-2">Edit Documents</h2>
</div>
<div class="container">
  <div class="card bg-dark text-white">
      <div class="card-body">
        <h5><%=raw @document.title %></h5>
        <br>
        <%=raw @document.body %>
        <br />
        <br>
        <%= link_to "Edit", edit_editor_path(@document.id), :class => 'btn btn-info' %>
        <%= link_to "Delete", editor_path(@document), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-danger' %>
        <%= link_to 'Download', download_path(@document), :class => 'btn btn-success' %>
      </div>
  </div>
</div>

app/views/editor/upload.html.erb
<div class="header" align="center">
  <h2 class="bg-danger pt-2 pb-2">Upload a File</h2>
</div>
<div class="container" align="center">

  <%= form_tag(:controller => :editor, :action => :fileupload, :multipart => true)  do  %>
    <%= file_field( :post, :attached, accept: 'text/html', class: "btn btn-secondary") %>
    <%= submit_tag "Upload", class: 'btn btn-info' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Corundum Text Editor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('cfavicon.png'), :rel => 'icon', :type =>  'image/png' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
      <div>
        <%= link_to image_tag("clogo.png", :alt => "Corundum", class: "navbar-brand", height: "30"), home_path %>
        <%= link_to image_tag("cfavicon.png", :alt => "ruby", class: "navbar-brand", height: "30"), home_path %>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-expanded="false">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item <%= active_class(home_path) %>">
            <%= link_to "Home", home_path, {:class=>"nav-link"} %>
          </li>
          <li class="nav-item <%= active_class(new_editor_path) %>">
            <%= link_to "New", new_editor_path, {:class=>"nav-link"} %>
          </li>
          <li class="nav-item <%= active_class(info_path) %>">
            <%= link_to "Information", info_path, {:class=>"nav-link"} %>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>